In [1]:

import pandas as pd
from leviVSchub import *

In [2]:
summary = load_summary_intervals("summary_enriched.json")

df_intervals = intervals_to_dataframe(summary)

df_intervals.head()

,run,day,start_time,end_time,duration,leg_type,boat,name,mast,total_weight,master_leeward,avg_SOG,SOG_var,avg_TWS,avg_TWA,SOG_ref,pol_ratio,stability
0,25_11_2025_Run1,25_11_2025,1.764078e+09,1.764079e+09,65.001,upwind,1,Gian Stragiotti,Chub,112.1,False,21.081679,0.685094,20.236901,32.776496,22.866727,92.193690,0.959474
1,25_11_2025_Run1,25_11_2025,1.764078e+09,1.764079e+09,65.001,upwind,2,Max Maeder,Levi,111.5,True,21.322137,0.575966,20.222497,32.185617,22.864521,93.254248,0.959474
2,25_11_2025_Run1,25_11_2025,1.764079e+09,1.764079e+09,37.000,downwind,1,Gian Stragiotti,Chub,112.1,False,32.354667,1.023546,20.244787,-150.833800,30.059314,107.636077,0.938433
3,25_11_2025_Run1,25_11_2025,1.764079e+09,1.764079e+09,37.000,downwind,2,Max Maeder,Levi,111.5,True,32.810667,0.948195,20.252175,-154.113191,30.099028,109.009056,0.938433
4,25_11_2025_Run2,25_11_2025,1.764079e+09,1.764079e+09,68.515,upwind,1,Gian Stragiotti,Chub,112.1,True,21.044928,1.076835,24.750529,30.935558,22.860999,92.056028,0.943485

In [3]:
df_paired = build_paired_intervals(df_intervals)
df_paired.head(5)

,run,boat1_day,start_time,end_time,boat1_duration,leg_type,boat1_name,boat1_mast,boat1_total_weight,boat1_master_leeward,...,boat2_avg_TWS,boat2_avg_TWA,boat2_SOG_ref,boat2_pol_ratio,boat2_stability,d_pol_ratio,d_avg_SOG,d_avg_SOG_mast,d_weight_mast,levi_rider
0,25_11_2025_Run1,25_11_2025,1.764078e+09,1.764079e+09,65.001,upwind,Gian Stragiotti,Chub,112.1,False,...,20.222497,32.185617,22.864521,93.254248,0.959474,1.060557,0.240458,0.240458,-0.6,Max Maeder
1,25_11_2025_Run1,25_11_2025,1.764079e+09,1.764079e+09,37.000,downwind,Gian Stragiotti,Chub,112.1,False,...,20.252175,-154.113191,30.099028,109.009056,0.938433,1.372979,0.456000,0.456000,-0.6,Max Maeder
2,25_11_2025_Run2,25_11_2025,1.764079e+09,1.764079e+09,68.515,upwind,Gian Stragiotti,Chub,112.1,True,...,24.761937,30.601038,22.860261,94.737529,0.943485,2.681501,0.612319,0.612319,-0.6,Max Maeder
3,25_11_2025_Run2,25_11_2025,1.764079e+09,1.764079e+09,33.516,downwind,Gian Stragiotti,Chub,112.1,True,...,22.621696,-156.655570,30.157696,110.541483,0.941421,4.469691,1.394118,1.394118,-0.6,Max Maeder
4,25_11_2025_Run3,25_11_2025,1.764079e+09,1.764079e+09,64.483,upwind,Gian Stragiotti,Chub,112.1,False,...,21.631589,32.178469,22.864497,94.829584,0.953840,-1.758173,-0.403077,-0.403077,-0.6,Max Maeder

# I. First analysis: means and t-tests

In [4]:
df = df_intervals.copy()

leg_mast = pd.crosstab(df["leg_type"], df["mast"])
print("Leg-type exposure by mast:")
for mast in leg_mast.columns:
    total = leg_mast[mast].sum()
    for leg in leg_mast.index:
        n = leg_mast.loc[leg, mast]
        print(
            f"- {mast}: {n} intervals ({100*n/total:.3f}%) were {leg}."
        )
print()

rider_mast = pd.crosstab(df["name"], df["mast"])
print("Rider–mast exposure:")
for rider in rider_mast.index:
    total = rider_mast.loc[rider].sum()
    chub_n = rider_mast.loc[rider, "Chub"]
    levi_n = rider_mast.loc[rider, "Levi"]
    print(
        f"- {rider} sailed {chub_n} intervals on Chub ({100*chub_n/total:.1f}%) "
        f"and {levi_n} on Levi ({100*levi_n/total:.3f}%)."
    )
print()

mean_by_mast(df, "All legs")
mean_by_mast(df[df["leg_type"] == "upwind"], "Upwind only")
mean_by_mast(df[df["leg_type"] == "downwind"], "Downwind only")

Leg-type exposure by mast:
- Chub: 27 intervals (48.214%) were downwind.
- Chub: 29 intervals (51.786%) were upwind.
- Levi: 27 intervals (48.214%) were downwind.
- Levi: 29 intervals (51.786%) were upwind.

Rider–mast exposure:
- Gian Stragiotti sailed 31 intervals on Chub (55.4%) and 25 on Levi (44.643%).
- Max Maeder sailed 25 intervals on Chub (44.6%) and 31 on Levi (55.357%).

======================================================================
All legs
Average conditions — TWS: 16.576/16.577 kn, TWA: -60.538/-60.911°, Weight: 111.812/111.788 kg (Levi / Chub).
Mean SOG difference (Levi − Chub): -0.142 kn. Chub is faster on average in the raw data.
According to the Welch t-test on avg_SOG: t = -0.15, p = 0.885
The difference in mean SOG is not statistically significant (p = 0.885 ≥ 0.05).
======================================================================
Upwind only
Average conditions — TWS: 16.874/16.874 kn, TWA: 30.229/29.318°, Weight: 111.814/111.786 kg (Levi / Chub).
Mean SOG difference (Levi − Chub): 0.107 kn. Levi is faster on average in the raw data.
According to the Welch t-test on avg_SOG: t = 0.21, p = 0.831
The difference in mean SOG is not statistically significant (p = 0.831 ≥ 0.05).
======================================================================
Downwind only
Average conditions — TWS: 16.257/16.258 kn, TWA: -158.028/-157.824°, Weight: 111.811/111.789 kg (Levi / Chub).
Mean SOG difference (Levi − Chub): -0.409 kn. Chub is faster on average in the raw data.
According to the Welch t-test on avg_SOG: t = -1.25, p = 0.217
The difference in mean SOG is not statistically significant (p = 0.217 ≥ 0.05).

# II. OLS Regression, predicting SOG(Levi) − SOG(Chub) in order to reduce effect of external conditions

## 1) General OLS

In [5]:
# SOG model
results = analyze_mast_effect(df_paired)
print(results["sog_model"].summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:         d_avg_SOG_mast   R-squared:                       0.209
Model:                            OLS   Adj. R-squared:                  0.163
Method:                 Least Squares   F-statistic:                     5.482
Date:                Tue, 12 May 2026   Prob (F-statistic):            0.00238
Time:                        14:29:19   Log-Likelihood:                -95.549
No. Observations:                  56   AIC:                             199.1
Df Residuals:                      52   BIC:                             207.2
Df Model:                           3
Covariance Type:                  HC3
===================================================================================================
                                      coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------------
Intercept                          -1.3400      0.466     -2.875      0.004      -2.254      -0.426
C(leg_type)[T.upwind]               0.5201      0.377      1.381      0.167      -0.218       1.258
C(boat1_master_leeward)[T.True]     0.4932      0.440      1.122      0.262      -0.368       1.355
C(levi_rider)[T.Max Maeder]         1.2483      0.410      3.046      0.002       0.445       2.052
==============================================================================
Omnibus:                       85.117   Durbin-Watson:                   1.803
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1521.692
Skew:                           4.161   Prob(JB):                         0.00
Kurtosis:                      27.143   Cond. No.                         4.05
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

## 2) Upwind OLS

In [6]:
df_paired_upwind = df_paired[df_paired["leg_type"] == "upwind"]
model_upwind = analyze_mast_effect_by_leg(df_paired_upwind, "UPWIND ONLY")

======================================================================
Paired OLS — UPWIND ONLY
N paired intervals: 29
                            OLS Regression Results
==============================================================================
Dep. Variable:         d_avg_SOG_mast   R-squared:                       0.100
Model:                            OLS   Adj. R-squared:                  0.031
Method:                 Least Squares   F-statistic:                    0.6380
Date:                Tue, 12 May 2026   Prob (F-statistic):              0.536
Time:                        14:29:19   Log-Likelihood:                -55.947
No. Observations:                  29   AIC:                             117.9
Df Residuals:                      26   BIC:                             122.0
Df Model:                           2
Covariance Type:                  HC3
===================================================================================================
                                      coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------------
Intercept                          -0.7480      0.461     -1.624      0.104      -1.651       0.155
C(boat1_master_leeward)[T.True]     0.8728      0.782      1.117      0.264      -0.659       2.405
C(levi_rider)[T.Max Maeder]         0.7858      0.710      1.107      0.268      -0.605       2.177
==============================================================================
Omnibus:                       60.403   Durbin-Watson:                   2.036
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              495.714
Skew:                           4.227   Prob(JB):                    2.28e-108
Kurtosis:                      21.406   Cond. No.                         3.43
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

## 2) Downwind OLS

In [7]:
df_paired_downwind = df_paired[df_paired["leg_type"] == "downwind"]
model_downwind = analyze_mast_effect_by_leg(df_paired_downwind, "DOWNWIND ONLY")

======================================================================
Paired OLS — DOWNWIND ONLY
N paired intervals: 27
                            OLS Regression Results
==============================================================================
Dep. Variable:         d_avg_SOG_mast   R-squared:                       0.591
Model:                            OLS   Adj. R-squared:                  0.557
Method:                 Least Squares   F-statistic:                     15.49
Date:                Tue, 12 May 2026   Prob (F-statistic):           4.79e-05
Time:                        14:29:19   Log-Likelihood:                -28.793
No. Observations:                  27   AIC:                             63.59
Df Residuals:                      24   BIC:                             67.47
Df Model:                           2
Covariance Type:                  HC3
===================================================================================================
                                      coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------------
Intercept                          -1.4223      0.394     -3.614      0.000      -2.194      -0.651
C(boat1_master_leeward)[T.True]     0.1210      0.334      0.363      0.717      -0.533       0.775
C(levi_rider)[T.Max Maeder]         1.7189      0.350      4.914      0.000       1.033       2.405
==============================================================================
Omnibus:                        8.948   Durbin-Watson:                   1.948
Prob(Omnibus):                  0.011   Jarque-Bera (JB):                7.075
Skew:                          -1.105   Prob(JB):                       0.0291
Kurtosis:                       4.187   Cond. No.                         3.59
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

# III. Rider-specific unpaired analysis
## 0 ) All riders

In [8]:
model_interaction = smf.ols(
    "avg_SOG ~ C(mast) * C(name) + C(leg_type) + avg_TWS + C(master_leeward)",
    data=df_intervals
).fit(cov_type="HC3")

print(model_interaction.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                avg_SOG   R-squared:                       0.919
Model:                            OLS   Adj. R-squared:                  0.915
Method:                 Least Squares   F-statistic:                     319.6
Date:                Tue, 12 May 2026   Prob (F-statistic):           4.69e-65
Time:                        14:29:19   Log-Likelihood:                -201.16
No. Observations:                 112   AIC:                             416.3
Df Residuals:                     105   BIC:                             435.3
Df Model:                           6
Covariance Type:                  HC3
=========================================================================================================
                                            coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------------------
Intercept                                33.8575      0.878     38.540      0.000      32.136      35.579
C(mast)[T.Levi]                          -0.8061      0.514     -1.567      0.117      -1.814       0.202
C(name)[T.Max Maeder]                    -0.0333      0.442     -0.075      0.940      -0.899       0.832
C(leg_type)[T.upwind]                    -9.6995      0.303    -31.964      0.000     -10.294      -9.105
C(master_leeward)[T.True]                -0.1725      0.331     -0.522      0.602      -0.820       0.475
C(mast)[T.Levi]:C(name)[T.Max Maeder]     1.2508      0.521      2.399      0.016       0.229       2.273
avg_TWS                                  -0.1091      0.046     -2.373      0.018      -0.199      -0.019
==============================================================================
Omnibus:                      131.139   Durbin-Watson:                   1.299
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             3459.548
Skew:                          -3.958   Prob(JB):                         0.00
Kurtosis:                      29.051   Cond. No.                         93.0
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

# 1) Gian 
## 1) a. Gian mean and t tests

In [9]:
df_gian = df_intervals[df_intervals["name"] == "Gian Stragiotti"]
df_gian.head()

,run,day,start_time,end_time,duration,leg_type,boat,name,mast,total_weight,master_leeward,avg_SOG,SOG_var,avg_TWS,avg_TWA,SOG_ref,pol_ratio,stability
0,25_11_2025_Run1,25_11_2025,1.764078e+09,1.764079e+09,65.001,upwind,1,Gian Stragiotti,Chub,112.1,False,21.081679,0.685094,20.236901,32.776496,22.866727,92.193690,0.959474
2,25_11_2025_Run1,25_11_2025,1.764079e+09,1.764079e+09,37.000,downwind,1,Gian Stragiotti,Chub,112.1,False,32.354667,1.023546,20.244787,-150.833800,30.059314,107.636077,0.938433
4,25_11_2025_Run2,25_11_2025,1.764079e+09,1.764079e+09,68.515,upwind,1,Gian Stragiotti,Chub,112.1,True,21.044928,1.076835,24.750529,30.935558,22.860999,92.056028,0.943485
6,25_11_2025_Run2,25_11_2025,1.764079e+09,1.764079e+09,33.516,downwind,1,Gian Stragiotti,Chub,112.1,True,31.942647,1.109971,22.628309,-154.847779,30.114177,106.071791,0.941421
8,25_11_2025_Run3,25_11_2025,1.764079e+09,1.764079e+09,64.483,upwind,1,Gian Stragiotti,Chub,112.1,False,22.085385,0.657233,21.633331,32.509592,22.865615,96.587758,0.953840

In [10]:
print(pd.crosstab(df_gian["leg_type"], df_gian["mast"], normalize="index") * 100)

mean_by_mast(df_gian, "Gian – all legs")

df_gian_up = df_gian[df_gian["leg_type"] == "upwind"].copy()
mean_by_mast(df_gian_up, "Gian – upwind")

df_gian_down = df_gian[df_gian["leg_type"] == "downwind"].copy()
mean_by_mast(df_gian_down, "Gian – downwind")

mast           Chub       Levi
leg_type
downwind  55.555556  44.444444
upwind    55.172414  44.827586
======================================================================
Gian – all legs
Average conditions — TWS: 17.043/16.200 kn, TWA: -59.195/-62.156°, Weight: 112.200/112.100 kg (Levi / Chub).
Mean SOG difference (Levi − Chub): -0.960 kn. Chub is faster on average in the raw data.
According to the Welch t-test on avg_SOG: t = -0.70, p = 0.489
The difference in mean SOG is not statistically significant (p = 0.489 ≥ 0.05).
======================================================================
Gian – upwind
Average conditions — TWS: 17.171/16.632 kn, TWA: 32.125/27.546°, Weight: 112.200/112.100 kg (Levi / Chub).
Mean SOG difference (Levi − Chub): -0.173 kn. Chub is faster on average in the raw data.
According to the Welch t-test on avg_SOG: t = -0.20, p = 0.844
The difference in mean SOG is not statistically significant (p = 0.844 ≥ 0.05).
======================================================================
Gian – downwind
Average conditions — TWS: 16.905/15.739 kn, TWA: -158.126/-157.839°, Weight: 112.200/112.100 kg (Levi / Chub).
Mean SOG difference (Levi − Chub): -1.730 kn. Chub is faster on average in the raw data.
According to the Welch t-test on avg_SOG: t = -4.10, p = 0.000
The difference in mean SOG is statistically significant (p = 0.000 < 0.05).


## 1) b. Gian OLS all legs

In [11]:
model_gian = smf.ols(
    "avg_SOG ~ C(mast) + C(leg_type) + avg_TWS + C(master_leeward)",
    data=df_gian
).fit(cov_type="HC3")
print(model_gian.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                avg_SOG   R-squared:                       0.871
Model:                            OLS   Adj. R-squared:                  0.861
Method:                 Least Squares   F-statistic:                     147.5
Date:                Tue, 12 May 2026   Prob (F-statistic):           2.28e-27
Time:                        14:29:19   Log-Likelihood:                -113.97
No. Observations:                  56   AIC:                             237.9
Df Residuals:                      51   BIC:                             248.1
Df Model:                           4
Covariance Type:                  HC3
=============================================================================================
                                coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------
Intercept                    33.9161      1.292     26.245      0.000      31.383      36.449
C(mast)[T.Levi]              -0.8023      0.535     -1.501      0.133      -1.850       0.245
C(leg_type)[T.upwind]        -9.4733      0.568    -16.671      0.000     -10.587      -8.360
C(master_leeward)[T.True]    -0.1348      0.629     -0.214      0.830      -1.367       1.098
avg_TWS                      -0.1209      0.085     -1.423      0.155      -0.288       0.046
==============================================================================
Omnibus:                       79.898   Durbin-Watson:                   1.534
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1109.802
Skew:                          -3.906   Prob(JB):                    1.02e-241
Kurtosis:                      23.362   Cond. No.                         86.0
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

Again, levi reduces the avg_SOG of 1 knot, and it is definitely statistically significant (p = 0.006)

## 1) b. Gian OLS upwind

In [12]:
model_gian_up = smf.ols(
    "avg_SOG ~ C(mast) + avg_TWS + C(master_leeward)",
    data=df_gian_up
).fit(cov_type="HC3")

print(model_gian_up.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                avg_SOG   R-squared:                       0.078
Model:                            OLS   Adj. R-squared:                 -0.032
Method:                 Least Squares   F-statistic:                     3.350
Date:                Tue, 12 May 2026   Prob (F-statistic):             0.0350
Time:                        14:29:19   Log-Likelihood:                -65.136
No. Observations:                  29   AIC:                             138.3
Df Residuals:                      25   BIC:                             143.7
Df Model:                           3
Covariance Type:                  HC3
=============================================================================================
                                coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------
Intercept                    25.2167      2.534      9.952      0.000      20.250      30.183
C(mast)[T.Levi]              -0.0351      0.962     -0.037      0.971      -1.920       1.850
C(master_leeward)[T.True]    -0.4106      1.074     -0.382      0.702      -2.516       1.695
avg_TWS                      -0.1793      0.137     -1.310      0.190      -0.448       0.089
==============================================================================
Omnibus:                       53.414   Durbin-Watson:                   1.880
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              319.000
Skew:                          -3.720   Prob(JB):                     5.37e-70
Kurtosis:                      17.444   Cond. No.                         86.8
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

## 1) c. Gian OLS downwind

In [13]:
model_gian_down = smf.ols(
    "avg_SOG ~ C(mast) + avg_TWS + C(master_leeward)",
    data=df_gian_down
).fit(cov_type="HC3")

print(model_gian_down.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                avg_SOG   R-squared:                       0.418
Model:                            OLS   Adj. R-squared:                  0.342
Method:                 Least Squares   F-statistic:                     7.328
Date:                Tue, 12 May 2026   Prob (F-statistic):            0.00128
Time:                        14:29:19   Log-Likelihood:                -39.057
No. Observations:                  27   AIC:                             86.11
Df Residuals:                      23   BIC:                             91.30
Df Model:                           3
Covariance Type:                  HC3
=============================================================================================
                                coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------
Intercept                    32.8259      1.738     18.888      0.000      29.420      36.232
C(mast)[T.Levi]              -1.7176      0.467     -3.678      0.000      -2.633      -0.802
C(master_leeward)[T.True]     0.1767      0.592      0.299      0.765      -0.983       1.336
avg_TWS                      -0.0381      0.117     -0.324      0.746      -0.268       0.192
==============================================================================
Omnibus:                        5.552   Durbin-Watson:                   1.453
Prob(Omnibus):                  0.062   Jarque-Bera (JB):                3.665
Skew:                          -0.761   Prob(JB):                        0.160
Kurtosis:                       3.971   Cond. No.                         85.1
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

# 1) Max 
## 1) a. Max mean and t tests

In [14]:
df_max = df_intervals[df_intervals["name"] == "Max Maeder"]
df_max.head()

,run,day,start_time,end_time,duration,leg_type,boat,name,mast,total_weight,master_leeward,avg_SOG,SOG_var,avg_TWS,avg_TWA,SOG_ref,pol_ratio,stability
1,25_11_2025_Run1,25_11_2025,1.764078e+09,1.764079e+09,65.001,upwind,2,Max Maeder,Levi,111.5,True,21.322137,0.575966,20.222497,32.185617,22.864521,93.254248,0.959474
3,25_11_2025_Run1,25_11_2025,1.764079e+09,1.764079e+09,37.000,downwind,2,Max Maeder,Levi,111.5,True,32.810667,0.948195,20.252175,-154.113191,30.099028,109.009056,0.938433
5,25_11_2025_Run2,25_11_2025,1.764079e+09,1.764079e+09,68.515,upwind,2,Max Maeder,Levi,111.5,False,21.657246,0.738798,24.761937,30.601038,22.860261,94.737529,0.943485
7,25_11_2025_Run2,25_11_2025,1.764079e+09,1.764079e+09,33.516,downwind,2,Max Maeder,Levi,111.5,False,33.336765,0.725835,22.621696,-156.655570,30.157696,110.541483,0.941421
9,25_11_2025_Run3,25_11_2025,1.764079e+09,1.764079e+09,64.483,upwind,2,Max Maeder,Levi,111.5,True,21.682308,0.609418,21.631589,32.178469,22.864497,94.829584,0.953840

In [15]:
print(pd.crosstab(df_max["leg_type"], df_max["mast"], normalize="index") * 100)

mean_by_mast(df_max, "Max – all legs")

df_max_up = df_max[df_max["leg_type"] == "upwind"].copy()
mean_by_mast(df_max_up, "Max – upwind")

df_max_down = df_max[df_max["leg_type"] == "downwind"].copy()
mean_by_mast(df_max_down, "Max – downwind")

mast           Chub       Levi
leg_type
downwind  44.444444  55.555556
upwind    44.827586  55.172414
======================================================================
Max – all legs
Average conditions — TWS: 16.200/17.043 kn, TWA: -61.620/-59.367°, Weight: 111.500/111.400 kg (Levi / Chub).
Mean SOG difference (Levi − Chub): 0.550 kn. Levi is faster on average in the raw data.
According to the Welch t-test on avg_SOG: t = 0.40, p = 0.693
The difference in mean SOG is not statistically significant (p = 0.693 ≥ 0.05).
======================================================================
Max – upwind
Average conditions — TWS: 16.632/17.171 kn, TWA: 28.689/31.500°, Weight: 111.500/111.400 kg (Levi / Chub).
Mean SOG difference (Levi − Chub): 0.315 kn. Levi is faster on average in the raw data.
According to the Welch t-test on avg_SOG: t = 0.72, p = 0.480
The difference in mean SOG is not statistically significant (p = 0.480 ≥ 0.05).
======================================================================
Max – downwind
Average conditions — TWS: 15.739/16.905 kn, TWA: -157.950/-157.806°, Weight: 111.500/111.400 kg (Levi / Chub).
Mean SOG difference (Levi − Chub): 0.723 kn. Levi is faster on average in the raw data.
According to the Welch t-test on avg_SOG: t = 2.38, p = 0.025
The difference in mean SOG is statistically significant (p = 0.025 < 0.05).


## 1) b. Max OLS all legs

In [16]:
model_max = smf.ols(
    "avg_SOG ~ C(mast) + C(leg_type) + avg_TWS + C(master_leeward)",
    data=df_max
).fit(cov_type="HC3")  # robust SE
print(model_max.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                avg_SOG   R-squared:                       0.969
Model:                            OLS   Adj. R-squared:                  0.967
Method:                 Least Squares   F-statistic:                     406.1
Date:                Tue, 12 May 2026   Prob (F-statistic):           5.47e-38
Time:                        14:29:19   Log-Likelihood:                -73.018
No. Observations:                  56   AIC:                             156.0
Df Residuals:                      51   BIC:                             166.2
Df Model:                           4
Covariance Type:                  HC3
=============================================================================================
                                coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------
Intercept                    33.7592      0.780     43.280      0.000      32.230      35.288
C(mast)[T.Levi]               0.4587      0.268      1.709      0.087      -0.067       0.985
C(leg_type)[T.upwind]        -9.9258      0.260    -38.190      0.000     -10.435      -9.416
C(master_leeward)[T.True]    -0.2082      0.284     -0.732      0.464      -0.766       0.349
avg_TWS                      -0.0975      0.044     -2.208      0.027      -0.184      -0.011
==============================================================================
Omnibus:                       14.629   Durbin-Watson:                   1.772
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               16.590
Skew:                          -1.096   Prob(JB):                     0.000250
Kurtosis:                       4.517   Cond. No.                         91.8
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)


## 1) b. Max OLS upwind

In [17]:
model_max_up = smf.ols(
    "avg_SOG ~ C(mast) + avg_TWS + C(master_leeward)",
    data=df_max_up
).fit(cov_type="HC3")

print(model_max_up.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                avg_SOG   R-squared:                       0.493
Model:                            OLS   Adj. R-squared:                  0.433
Method:                 Least Squares   F-statistic:                     6.354
Date:                Tue, 12 May 2026   Prob (F-statistic):            0.00237
Time:                        14:29:19   Log-Likelihood:                -34.046
No. Observations:                  29   AIC:                             76.09
Df Residuals:                      25   BIC:                             81.56
Df Model:                           3
Covariance Type:                  HC3
=============================================================================================
                                coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------
Intercept                    25.8428      0.936     27.603      0.000      24.008      27.678
C(mast)[T.Levi]               0.2447      0.355      0.690      0.490      -0.450       0.940
C(master_leeward)[T.True]    -0.3933      0.363     -1.082      0.279      -1.105       0.319
avg_TWS                      -0.2039      0.057     -3.553      0.000      -0.316      -0.091
==============================================================================
Omnibus:                       26.880   Durbin-Watson:                   1.500
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               46.323
Skew:                          -2.145   Prob(JB):                     8.73e-11
Kurtosis:                       7.465   Cond. No.                         89.4
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)


## 1) b. Max OLS downwind

In [18]:
model_max_down = smf.ols(
    "avg_SOG ~ C(mast) + avg_TWS + C(master_leeward)",
    data=df_max_down
).fit(cov_type="HC3")

print(model_max_down.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                avg_SOG   R-squared:                       0.212
Model:                            OLS   Adj. R-squared:                  0.110
Method:                 Least Squares   F-statistic:                     2.446
Date:                Tue, 12 May 2026   Prob (F-statistic):             0.0896
Time:                        14:29:19   Log-Likelihood:                -30.832
No. Observations:                  27   AIC:                             69.66
Df Residuals:                      23   BIC:                             74.85
Df Model:                           3
Covariance Type:                  HC3
=============================================================================================
                                coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------
Intercept                    31.0462      1.091     28.450      0.000      28.907      33.185
C(mast)[T.Levi]               0.7662      0.352      2.174      0.030       0.075       1.457
C(master_leeward)[T.True]     0.0797      0.394      0.202      0.840      -0.693       0.852
avg_TWS                       0.0497      0.063      0.792      0.428      -0.073       0.173
==============================================================================
Omnibus:                        2.302   Durbin-Watson:                   1.345
Prob(Omnibus):                  0.316   Jarque-Bera (JB):                1.819
Skew:                          -0.485   Prob(JB):                        0.403
Kurtosis:                       2.178   Cond. No.                         94.6
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)